# Apps
bindsym $mod+b exec flatpak run app.zen_browser.zen
bindsym $mod+Shift+b exec flatpak run app.zen_browser.zen --private-window
bindsym $mod+Ctrl+b exec firefox
bindsym $mod+n exec wezterm -e yazi

# Workspace prev/next
bindsym $mod+Shift+Tab workspace prev
bindsym $mod+Tab workspace next

# Hide/unhide bar
bindsym $mod+Control+space bar mode toggle

bindsym $mod+Ctrl+l exec ~/.config/sway/scripts/locksway

# Clipboard
bindsym $mod+Shift+d exec ~/.local/bin/copyClip.sh
bindsym $mod+Ctrl+Shift+d exec cliphist list | rofi -dmenu -p "Delete selection:" | cliphist delete

# Print screen
bindsym Shift+Print exec ~/.config/sway/scripts/printRegion.sh

# Allow switching between workspaces with left and right swipes
bindgesture swipe:right workspace prev
bindgesture swipe:left workspace next
