
##############
# My configs #
##############
# Hide cursor after time
seat * hide_cursor 8000
# Keyboard
input * {
        xkb_layout "us"
        xkb_variant "intl"
        dwt enabled
        tap disabled
        natural_scroll disabled
        middle_emulation enabled
}
exec_always wl-paste --watch cliphist store
exec_always /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
exec_always ~/.config/sway/scripts/battery-warning.sh
