[[opener.set-wallpaper]]
run  = "killall swaybg; swaybg -m fill -i %s1"
for  = "linux"
desc = "Set as wallpaper"
orphan = true

[[opener.image]]
run  = "feh --scale-down --auto-zoom %*"
desc = "Open image with feh"
for  = "linux"

[[opener.loupe]]
run  = "loupe %*"
desc = "Open with Loupe"

[[open.prepend_rules]]
mime = "image/*"
use  = [ "image", "loupe", "set-wallpaper" ]

[[opener.text]]
run  = "nvim %*"
desc = "Edit text with Neovim"
for  = "linux"
block = true

[[open.prepend_rules]]
mime = "text/*"
use  = [ "text" ]

[[open.prepend_rules]]
mime = "text/csv"
use  = [ "text" ]
