#!/usr/bin/sh

# Tiago Minuzzi configs
# Mouse pointer
xsetroot -cursor_name left_ptr &
# Bar
$HOME/.config/polybar/launch.sh & 
# Display config
$HOME/.screenlayout/bspwm.sh &
#xrandr --output HDMI-1 --primary --left-of LVDS-1 --auto &
# Wallpaper
nitrogen --restore &
# Keybindings
sxhkd &
# Compositor
picom -f &
# BSPWM configs
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           4
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# Desktop specific windows
bspc rule -a VSCodium desktop='^2'
bspc rule -a Gedit desktop='^3'
bspc rule -a Soffice desktop='^3'
bspc rule -a Org.gnome.Nautilus desktop='^4'
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Rambox desktop='^7'
bspc rule -a Spotify desktop='^8'
bspc rule -a Firefox desktop='^10'
# Floating windows
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pulseeffects state=floating
