#!/usr/bin/sh

# Tiago Minuzzi configs
# Mouse pointer
xsetroot -cursor_name left_ptr &
# Bar
$HOME/.config/polybar/launch.sh & 
# Display config
$HOME/.screenlayout/bspwm.sh &
#xrandr --output HDMI-1 --primary --left-of LVDS-1 --auto &
# Wallpaper
nitrogen --restore &
# Keybindings
sxhkd &
# Compositor
picom -f &

bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           4
#bspc config top_padding          2
bscp config bottom_padding       4 

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Nitrogen state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
