#!/usr/bin/env bash

if [ $(which rofi) ];then
    rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
elif [ $(which dmenu) ];then
    greenclip print | sed '/^$/d' | dmenu -i -l 10 -p clipboard | xargs -r -d'\n' -I '{}' greenclip print '{}'
fi
