#!/usr/bin/env bash

if xrandr -q | grep 'HDMI-A-0 connected' > /dev/null;then
    xrandr --output HDMI-A-0 --primary --mode 1920x1080 --pos 1366x0 --output eDP --mode 1366x768 --pos 0x312 && \
        if command -v feh > /dev/null;then
            ~/.fehbg
        fi
else
    xrandr --output HDMI-A-0 --off --output eDP --primary --mode 1366x768 && \
        if command -v feh > /dev/null;then
            ~/.fehbg
        fi
fi
