#!/usr/bin/env bash

if xrandr -q | grep 'HDMI-A-0 connected';then
    xrandr --output HDMI-A-0 --primary --mode 1920x1080 --right-of eDP --output eDP --mode 1366x768 &&
    ~/.fehbg
else
    xrandr --output HDMI-A-0 --off --output eDP --primary --mode 1366x768 &&
    ~/.fehbg
fi
