#!/usr/bin/env bash

OPTIONS="Laptop\nDual\nHDMI"
SELECT=$(echo -e "$OPTIONS" | dmenu -i -p "Select display mode:")

case "$SELECT" in
    Laptop) xrandr --output HDMI-A-0 --off --output eDP --primary --mode 1366x768 &&
        ~/.fehbg ;;
    Dual) xrandr --output HDMI-A-0 --primary --mode 1920x1080 --right-of eDP --output eDP --mode 1366x768 &&
        ~/.fehbg ;;
    HDMI) xrandr --output HDMI-A-0 --primary --mode 1920x1080 --right-of eDP --output eDP --off &&
        ~/.fehbg ;;
esac
