#!/usr/bin/env bash

deletar=(.config/KDE
.config/Trolltech.conf
.config/akregatorrc
.config/autostart-scripts
.config/baloofilerc
.config/bluedevilglobalrc
.config/dolphinrc
.config/drkonqirc
.config/emaildefaults
.config/flameshotrc
.config/gtkrc
.config/kactivitymanagerd-statsrc
.config/kactivitymanagerdrc
.config/kateschemarc
.config/kcminputrc
.config/kconf_updaterc
.config/kde.org
.config/kded5rc
.config/kdedefaults
.config/kdeglobals
.config/kfontinstuirc
.config/kgammarc
.config/kglobalshortcutsrc
.config/khotkeysrc
.config/kmixrc
.config/konsolerc
.config/krunnerrc
.config/kscreenlockerrc
.config/ksmserverrc
.config/ksplashrc
.config/ktimezonedrc
.config/kwinrc
.config/kwinrulesrc
.config/kxkbrc
.config/libaccounts-glib
.config/plasma-localerc
.config/plasma-org.kde.plasma.desktop-appletsrc
.config/plasmarc
.config/plasmashellrc
.config/powerdevilrc
.config/powermanagementprofilesrc
.local/share/aurorae
.local/share/baloo
.local/share/dolphin
.local/share/icons
.local/share/kactivitymanagerd
.local/share/kcookiejar
.local/share/klipper
.local/share/knewstuff3
.local/share/konsole
.local/share/krunnerstaterc
.local/share/kscreen
.local/share/kxmlgui5
.local/share/plasma)

for item in ${deletar[@]}
do
    rm -r $item
done
